on:
    workflow_dispatch:
    pull_request:
      branches: [main, master]
    push:
      # only trigger on main/master branches, not on tags
      branches: [main, master]
  
name: quarto-render
jobs:
    quarto-linux:
        runs-on: ubuntu-latest
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source
        steps:
        # Obtain a copy of the repository on the runner
        - name: Check out repository
          uses: actions/checkout@v3

        # Install Quarto
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            # To install LaTeX to build PDF book 
            tinytex: true 

        # Setup pandoc (might be included with Quarto action?) 
        - uses: r-lib/actions/setup-pandoc@v2
        # Setup R
        - uses: r-lib/actions/setup-r@v2
          with:
            use-public-rspm: true

        # Handle installing R packages from DESCRIPTION file
        - uses: r-lib/actions/setup-r-dependencies@v2
        #  with:
        #    extra-packages: any::ggplot2, local::.
        
        # Download latest version of Python
        - uses: actions/setup-python@v4
          with:
            python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            cache: 'pip'
        
        # Install jupyter via pip if it is not part of your requirements.txt
        # - name: "Install Jupyter Notebooks via Pip"
        #  run: |
        #     pip install jupyter 
        
        # Install python dependencies from requirements via pip
        #- name: "Install Python dependencies via Pip"
        #  run: | 
        #     pip install -r requirements.txt

        # Back to our regularly scheduled Quarto output
        # Render the Quarto file
        - name: "Render working directory"
          uses: quarto-dev/quarto-actions/render@v2

        # Upload a tar file that will work with GitHub Pages
        # Make sure to set a retention day to avoid running into a cap
        # This artifact shouldn't be required after deployment onto pages was a success.
        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v3
          with: 
            retention-days: 1
            path: _book # This is the default output directory for Quarto books
        
        # Use an Action deploy to push the artifact onto GitHub Pages
        # This requires the `Action` tab being structured to allow for deployment
        # instead of using `docs/` or the `gh-pages` branch of the repository
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4

